doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    types:
      weather_info_id: Weather\Infrastructure\Persistence\Doctrine\Types\WeatherInfoIdType
      datetime_immutable: Weather\Infrastructure\Persistence\Doctrine\Types\DateTimeImmutableType
      point: Weather\Infrastructure\Persistence\Doctrine\Types\PointType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Weather:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping"
        prefix: 'Weather\Domain\Model'