#!/bin/sh

#bin/local-php-security-checker composer.lock

bin/php vendor/bin/phpcbf --standard=PSR12 ./src ./tests
bin/php vendor/bin/phpcs --standard=PSR12 ./src ./tests

bin/php vendor/bin/phpstan analyse --level=10 ./src --memory-limit 128G
bin/php vendor/bin/phpstan analyse --level=10 ./tests --memory-limit 256G

bin/phpunit --coverage-html ./var/coverage --testsuite all
