DateTimeParam:
  in:  query
  name: date
  date: date, in format "YYYY-MM-DD hh:mm(:ss(.uuuuuu))"
  description: date, in format "YYYY-MM-DD hh:mm(:ss(.uuuuuu))"
  required: true
  example: "2024-01-01 12:30"
  schema:
    $ref: '../models/types.yaml#/DateTime'

PointParam:
  in:  query
  name: point
  points: point as "[lat],[lon]"
  description: point as "[lat],[lon]"
  required: true
  example: 48.867,2.333
  schema:
    $ref: '../models/types.yaml#/Point'

PointsParam:
  in:  query
  name: points
  points: points as "[lat],[lon]", separated by ";"
  description: point as "[lat],[lon]", separated by ";"
  required: true
  example: 48.867,2.333;48.8605,2.3376
  schema:
    type: string
    example: 48.867,2.333;48.8605,2.3376

IdParam:
  in:  query
  name: id
  id: identifier of the corresponding weather
  description: identifier of the corresponding weather
  required: true
  example: "weather_db6e3f314cd5134de351a135fb315a35"
  schema:
    type: string
    example: "weather_db6e3f314cd5134de351a135fb315a35"

HistoricalParam:
  in: query
  name: historicalOnly
  historicalOnly: If the value is historical, null if it does not matter
  description: If the value is historical, null if it does not matter
  default: null
  example: false
  schema:
    type: bool
    example: false

ExactParam:
  in: query
  name: exact
  exact: If the search should be exact (true) or near (false)
  description: If the search should be exact (true) or near (false)
  default: false
  example: false
  schema:
    type: bool
    example: false

PathParam:
  in: query
  name: path
  path: the path of the file or directory
  description: the path of the file or directory
  required: true
  schema:
    type: string
    example: "/home/Downloads/weathers.json"

DatabaseParam:
  in: query
  name: db
  db: the database to import from
  description: the database to import from
  required: true
  schema:
    type: string
    example: "mysql:host=localhost:8080;dbname=weather"

TableParam:
  in: query
  name: table
  db: the table to import from
  description: the table to import from
  required: true
  schema:
    type: string
    example: "weather"

UserParam:
  in: query
  name: user
  user: The user to log in as
  description: The user to log in as
  schema:
    type: string
    example: "user"

PasswordParam:
  in: query
  name: pwd
  pwd: the login password
  description: the login password
  default: ""
  schema:
    type: string
